# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "necrophonic"

[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "J Gregory"
  description = "Necrophonic Landing Page"
  bio = "Artist. Musician. Software Engineer\n&nbsp;"
  avatar = "img/gopher.png"
  favicon = "img/favicon.ico"
  error404 = "There is no such page"
  email = "n3crophonic+github@gmail.com"

  [params.contact]
    github = "https://github.com/necrophonic"
    twitter = "https://twitter.com/n3crophonic"

